### ISSUE TITLE
Not recieving code while signing through email

### ISSUE THREAD

**Issue by techyaura** [paranoidguy/databunker#1]
I was trying to try out the demo via https://demo.paranoidguy.com/. But I am not able to receive the code.

**Comment by stremovsky** [comment]
Hi

You can use "hard" coded user in demo version. User phone: "4444", code: "4444".

You need to confirm to allow sending access code (that is not send in demo version).

**Comment by techyaura** [comment]
Thanks @stremovsky , it's work well for the credentials you have provided.

And @stremovsky I am interested in contributing for this project. So then definitely we can make it more awesome.
But I don't have proper knowledge about GDPR, so what will you recommend me to understand GDPR in a quick way, so that I can work on it with you. 
I know `there is nothing like quick but I mean to say some resource where I should start.

**Comment by stremovsky** [comment]
Hi

I loke to follow this guide - has many good articles:

https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/principles/lawfulness-fairness-and-transparency/
